GET http://localhost:3000

### SEND FETCH SONGS REQUEST
GET http://localhost:3000/songs

### Pagniation
GET http://localhost:3000/songs/?page=1&limit=10

### Find SONGS REQUEST
GET http://localhost:3000/songs/3

### Create New SONGS REQUEST
POST http://localhost:3000/songs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIzLCJlbWFpbCI6InZpZXQzNEBnaG1haWwuY29tIiwiaWF0IjoxNzM2MDA0NTIzLCJleHAiOjE3MzYwOTA5MjN9.barfZhttb6Ijrst48UQP3ltecF5ia0gIUaBG4nzLv6A

{
"title": "lasting lover",
"artists": [
    "Siagla",
    "Martin",
    "John"
],
"releasedDate" : "2022-09-29",
"duration" :"02:34"
}



### Update SONGS REQUEST
PUT http://localhost:3000/songs/3
Content-Type: application/json

{
"title": "You for Me 3",
"artists": ["Siagla", "Yan", "Ny"],
"releasedDate": "2022-09-30",
"duration": "02:45",
"lyrics": "Sby, you're my adrenaline. Brought out this other side of me Yo don't even I wanted you for me I dance to every song like it's aboutya I drink 'til I kiss someone who looks like ya"
}

### DELETE SONG
DELETE http://localhost:3000/songs/4

### CREATE PLAYLIST

POST http://localhost:3000/playlists
Content-Type: application/json

{
"name": "Feel Good Now",
"songs": [3],
"user": 1
}


### Signup User
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
"firstName": "viet",
"lastName": "doe",
"email": "xfdsxvx@ghmail.com",
"password": "123456"
}

### Login User
POST http://localhost:3000/auth/login
Content-Type: application/json

{
"email": "viet34@ghmail.com",
"password": "123456"
}

### Test protected route

GET http://localhost:3000/auth/profile
Authorization: Bearer b89812f0-e7a5-4970-9ec6-c3dcf01c2c7c

