GET http://localhost:3000

### SEND FETCH SONGS REQUEST
GET http://localhost:3000/songs

### Find SONGS REQUEST
GET http://localhost:3000/songs/3

### Create New SONGS REQUEST
POST http://localhost:3000/songs
Content-Type: application/json

{
"title": "lasting lover",
"artists": [
    "Siagla",
    "Martin",
    "John"
],
"releasedDate" : "2022-09-29",
"duration" :"02:34"
}



### Update SONGS REQUEST
PUT http://localhost:3000/songs/3
Content-Type: application/json

{
"title": "You for Me 3",
"artists": ["Siagla", "Yan", "Ny"],
"releasedDate": "2022-09-30",
"duration": "02:45",
"lyrics": "Sby, you're my adrenaline. Brought out this other side of me Yo don't even I wanted you for me I dance to every song like it's aboutya I drink 'til I kiss someone who looks like ya"
}

### Update SONGS REQUEST
DELETE http://localhost:3000/songs/4
